name: Deploy on EC2

on:
  push:
    branches: [main]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Build & Deploy
        uses: actions/checkout@v4

      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1
        with:
          host: 15.206.189.207 
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd practice/git-try-act
            git pull origin main
            pm2 restart all
            echo "Deployment script finished!"
